name: biobb_pmx
owner: chemteam
description: "Biobb_pmx is the Biobb module collection to perform PMX executions"
homepage_url: https://github.com/bioexcel/biobb_pytorch
long_description: |
    Biobb_pmx is the Biobb module collection to perform PMX executions.
    Biobb (BioExcel building blocks) packages are Python building blocks that
    create new layer of compatibility and interoperability over popular bioinformatics tools.
    The latest documentation of this package can be found in our readthedocs site:
    [latest API documentation](https://biobb-pmx.readthedocs.io/en/latest/).
remote_repository_url: https://github.com/galaxycomputationalchemistry/galaxy-tools-compchem/tree/master/tools/biobb_pmx
type: unrestricted
categories:
  - pmx
  - energy
maintainers:
  - PauAndrio
  - gbayarri
  - adamhospital