name: biobb_structure_utils
owner: chemteam
description: "Biobb_structure_utils is the Biobb module collection to modify or extract information from a PDB structure file."
homepage_url: https://github.com/bioexcel/biobb_pytorch
long_description: |
    Biobb_structure_utils is the Biobb module collection to modify or extract information from a PDB structure file..
    Biobb (BioExcel building blocks) packages are Python building blocks that
    create new layer of compatibility and interoperability over popular bioinformatics tools.
    The latest documentation of this package can be found in our readthedocs site:
    [latest API documentation](https://biobb-structure-utils.readthedocs.io/en/latest/).
remote_repository_url: https://github.com/galaxycomputationalchemistry/galaxy-tools-compchem/tree/master/tools/biobb_structure_utils
type: unrestricted
categories:
  - structure
  - protein
  - heteroatom
  - biopython
maintainers:
  - PauAndrio
  - gbayarri
  - adamhospital