name: biobb_pytorch
owner: chemteam
description: "biobb_pytorch is the Biobb module collection to train and create ML & DL models using the popular PyTorch Python library"
homepage_url: https://github.com/bioexcel/biobb_pytorch
long_description: |
    biobb_pytorch is the Biobb module collection to train and create ML & DL models using the popular PyTorch Python library.
    Biobb (BioExcel building blocks) packages are Python building blocks that
    create new layer of compatibility and interoperability over popular bioinformatics tools.
    The latest documentation of this package can be found in our readthedocs site:
    [latest API documentation](https://biobb-pytorch.readthedocs.io/en/latest/).
remote_repository_url: https://github.com/galaxycomputationalchemistry/galaxy-tools-compchem/tree/master/tools/biobb_pytorch
type: unrestricted
categories:
  - md
  - molecular
  - dynamics
  - pytorch
maintainers:
  - PauAndrio
  - gbayarri
  - adamhospital