name: biobb_pytorch
owner: chemteam
description: "Biobb_pytorch is a BioBB category for creating and training Machine Learning and Deep Learning models using PyTorch. It allows building, training, and evaluating Molecular Dynamics AutoEncoders (MDAE) and other PyTorch-based models for analyzing molecular dynamics trajectories."
homepage_url: https://github.com/bioexcel/biobb_pytorch
long_description: |
    Biobb_pytorch is a BioBB category for creating and training Machine Learning and Deep Learning models using PyTorch. It allows building, training, and evaluating Molecular Dynamics AutoEncoders (MDAE) and other PyTorch-based models for analyzing molecular dynamics trajectories..
    Biobb (BioExcel building blocks) packages are Python building blocks that
    create new layer of compatibility and interoperability over popular bioinformatics tools.
    The latest documentation of this package can be found in our readthedocs site:
    [latest API documentation](https://biobb-pytorch.readthedocs.io/en/latest/).
remote_repository_url: https://github.com/galaxycomputationalchemistry/galaxy-tools-compchem/tree/master/tools/biobb_pytorch
type: unrestricted
categories:
  - pytorch
  - machine learning
  - deep learning
  - autoencoder
  - molecular dynamics
  - neural networks
  - MDAE
maintainers:
  - PauAndrio
  - gbayarri
  - adamhospital