name: biobb_model
owner: chemteam
description: "Biobb_model is the Biobb module collection to check and model 3d structures, create mutations or reconstruct missing atoms"
homepage_url: https://github.com/bioexcel/biobb_pytorch
long_description: |
    Biobb_model is the Biobb module collection to check and model 3d structures, create mutations or reconstruct missing atoms.
    Biobb (BioExcel building blocks) packages are Python building blocks that
    create new layer of compatibility and interoperability over popular bioinformatics tools.
    The latest documentation of this package can be found in our readthedocs site:
    [latest API documentation](https://biobb-model.readthedocs.io/en/latest/).
remote_repository_url: https://github.com/galaxycomputationalchemistry/galaxy-tools-compchem/tree/master/tools/biobb_model
type: unrestricted
categories:
  - model
  - mutate
  - side chain
  - amide
  - chirality
maintainers:
  - PauAndrio
  - gbayarri
  - adamhospital