name: biobb_cp2k
owner: chemteam
description: "Biobb_cp2k is a BioBB category for CP2K QM package, allowing setup and simulation of QM simulations using CP2K QM package"
homepage_url: https://github.com/bioexcel/biobb_pytorch
long_description: |
    Biobb_cp2k is a BioBB category for CP2K QM package, allowing setup and simulation of QM simulations using CP2K QM package.
    Biobb (BioExcel building blocks) packages are Python building blocks that
    create new layer of compatibility and interoperability over popular bioinformatics tools.
    The latest documentation of this package can be found in our readthedocs site:
    [latest API documentation](https://biobb-cp2k.readthedocs.io/en/latest/).
remote_repository_url: https://github.com/galaxycomputationalchemistry/galaxy-tools-compchem/tree/master/tools/biobb_cp2k
type: unrestricted
categories:
  - CP2K
  - QM
maintainers:
  - PauAndrio
  - gbayarri
  - adamhospital